# commands to specify testing environments
language: python
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
    - python: 3.8
      dist: xenial
      sudo: true
    - python: nightly
      dist: xenial
      sudo: true
    - name: Python (homebrew)
      os: osx
      osx_image: xcode11.3
      language: shell       # 'language: python' is an error on Travis CI macOS
      addons:
        homebrew:
          update: true
          packages: python@3.8
      before_install:
        - pip3 install virtualenv
        - virtualenv -p $(brew --prefix)/opt/python@3.8/bin/python3 ~/venv
        - source ~/venv/bin/activate
    - name: Python (choco)
      os: windows
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python3
      env: PATH=/c/Python38:/c/Python38/Scripts:$PATH
  allow_failures:
    - python: nightly

branches:
  only:
    - master
    - /^[0-9].+$/

# command to install dependencies
install:
  - pip install -r test-requirements.txt

# command to run tests
script:
  # modified discover to handle namespace package
  python -m unittest discover -s nionswift_plugin/usim/test/ -p '*_test.py'

# command to deploy to pypi on tags
deploy:
  provider: pypi
  user: "cmeyer"
  password:
    secure: "VOazGUnAK7kAecmwb8q/PvetCg2a6BWzzq3P6Qit9/M/8fV/tk24qBuWhudUHqGz4FQG6GIPes0lERZfib+IBFKlRdxEHNn6NIewGkClwUQ3SJgO1B/HHTBfiAFfVcBTKcOSGzXsmJmY+zRhkZ54enfT3HPUYqh8ojzEq09olqkDvoFD5/chDLXb745I73hf/VkE+kWwbvVZY55Qyff/q8PjmdM/t6BWHU3CqmBG5F3LKpOoEewstdR7hdPLHLAzp6+zYgoV04z0pD3/NhB/VxO7cKXBA17IDqae1Gw8FH+O0renVdQAXf2KdtUBYcyeYX8dlWod4bCxksZ0ZejA0CE+fNfr/bMMCZqaB9Z4c2iDf5SnPchMY0n6E2CxlxLjHpagkWQZq16YTgLvRWhjCm263rHIwxtNIKtzgxlzATHZU465jEI3vbkK3StLGLlL8FZEoLV9U8DdgtkYdFmmz1nYACxaUuST2ZaDQtYvWZRLZF9mQigSTANT6ZoJDGzuq3Td83JwgTu3Q2g55wACmMs5a946rMXxO9Gjmi/HodYjQK3OyKtofW1CaV8wo6/tuhZwH17uTJf0DpEGRDV6+9MM31j9qR+4CcxLhKznLd9GrQ3i9psTNoH6shJgzPHPVcrCJ/Q+S2uVCT4FAVE0rbZaWngWWtbkmD6eOuGg3qo="
  on:
    tags: true
    python: '3.7'
    branch: master
  distributions: "sdist bdist_wheel" # Your distributions here
